namespace BaristaLabs.ChromeDevTools.Runtime.Network
{
    using Newtonsoft.Json;

    /// <summary>
    /// Enables tracking for the Reporting API, events generated by the Reporting API will now be delivered to the client.
    /// Enabling triggers 'reportingApiReportAdded' for all existing reports.
    /// </summary>
    public sealed class EnableReportingApiCommand : ICommand
    {
        private const string ChromeRemoteInterface_CommandName = "Network.enableReportingApi";
        
        [JsonIgnore]
        public string CommandName
        {
            get { return ChromeRemoteInterface_CommandName; }
        }

        /// <summary>
        /// Whether to enable or disable events for the Reporting API
        /// </summary>
        [JsonProperty("enable")]
        public bool Enable
        {
            get;
            set;
        }
    }

    public sealed class EnableReportingApiCommandResponse : ICommandResponse<EnableReportingApiCommand>
    {
    }
}